set(_CATKIN_CURRENT_PACKAGE "assignment5_object_tracking")
set(assignment5_object_tracking_VERSION "0.0.0")
set(assignment5_object_tracking_MAINTAINER "anas <anas@todo.todo>")
set(assignment5_object_tracking_PACKAGE_FORMAT "2")
set(assignment5_object_tracking_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(assignment5_object_tracking_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(assignment5_object_tracking_BUILDTOOL_DEPENDS "catkin")
set(assignment5_object_tracking_BUILDTOOL_EXPORT_DEPENDS )
set(assignment5_object_tracking_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(assignment5_object_tracking_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(assignment5_object_tracking_TEST_DEPENDS )
set(assignment5_object_tracking_DOC_DEPENDS )
set(assignment5_object_tracking_URL_WEBSITE "")
set(assignment5_object_tracking_URL_BUGTRACKER "")
set(assignment5_object_tracking_URL_REPOSITORY "")
set(assignment5_object_tracking_DEPRECATED "")